name: Build and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-lint:
    name: Build & Lint App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run format check
      #   run: |
      #     pip install black flake8 isort
      #     black --check .
      #     isort --check-only .
      #     flake8 .

      - name: Build containers using Makefile
        run: make up

      - name: Shut down containers
        if: always()
        run: make down
